---

- import_tasks: register_vars.yml

- name: create directory if they don't exist
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: 0775
  loop:
    - /home/vishnunimmalapudi/confluent.temp/confluent
    - /home/vishnunimmalapudi/confluent.temp/java
    - /home/vishnunimmalapudi/confluent.temp/service/zookeeper
    - /home/vishnunimmalapudi/confluent.temp/confluent/data/zoo-dataDir
    - /home/vishnunimmalapudi/confluent.temp/tmp/kafka-10-logs


- name: download-confluent-kafka
  shell: 'sudo curl -O http://packages.confluent.io/archive/6.2/confluent-community-6.2.0.tar.gz'
  args:
    chdir: /home/vishnunimmalapudi/confluent.temp/confluent


- name: extract files from confluent.tar
  shell: 'sudo tar xzf confluent-community-6.2.0.tar.gz'
  args:
    chdir: /home/vishnunimmalapudi/confluent.temp/confluent

- name: download-java
  shell: 'sudo curl -O https://download.java.net/java/GA/jdk11/13/GPL/openjdk-11.0.1_linux-x64_bin.tar.gz'
  args:
    chdir: /home/vishnunimmalapudi/confluent.temp/java


- name: extract files from java.tar
  shell: 'sudo tar xzf openjdk-11.0.1_linux-x64_bin.tar.gz'
  args:
    chdir: /home/vishnunimmalapudi/confluent.temp/java

- name: copy paste zoo props
  shell: 'sudo cp {{installation_dir_path}}/confluent/confluent-6.2.0/etc/kafka/zookeeper.properties {{installation_dir_path}}/service/zookeeper/zookeeper.properties'




- name: Configure zookeeper.properties
  template:
    src: zookeeper.properties.j2
    dest: /home/vishnunimmalapudi/confluent.temp/service/zookeeper/zookeeper.properties

- name: add bashrc lines
  blockinfile:
    state: present
    insertafter: EOF
    dest: /home/vishnunimmalapudi/.bashrc
    
    content: |
      export JAVA_HOME=/home/vishnunimmalapudi/confluent.temp/java/jdk-11.0.1
      export CONFLUENT_HOME=/home/vishnunimmalapudi/confluent.temp/confluent/confluent-6.2.0
      export CMAK_HOME=/home/vishnunimmalapudi/confluent.temp/confluent/cmak-3.0.0.5
      export PATH=$PATH:$JAVA_HOME/bin:$CONFLUENT_HOME/bin:$CMAK_HOME/bin
      export ZK_HOSTS="fraboxpd0071.de.db.com:2181,fraboxpd0072.de.db.com:2181"
      alias services.status='systemctl list-units --type service --all | grep label-app'
      alias service.log='sudo journalctl -f -n 500 -u' 


- name: Creates zookeeper cluster directories
  file: 
    path: /home/vishnunimmalapudi/confluent.temp/confluent/data/zoo-dataDir
    state: directory

- name: Configure zookeeper myid
  template:
    src: myid.j2
    dest: /home/vishnunimmalapudi/confluent.temp/confluent/data/zoo-dataDir/myid

- name: Install zookeeper as service
  copy: 
    src: zookeeper_ansible.service
    dest: /etc/systemd/system/
    owner: root 
    mode: 777
  become: yes
  notify:
    - restart zookeeper service


- name: Install zookeeper.run
  copy:
    src: zookeeper.run.sh
    dest: /home/vishnunimmalapudi/confluent.temp/service/zookeeper/
    owner: root
    mode: 777
  become: yes
  notify:
    - restart zookeeper service


- name: Install zookeeper.stop
  copy:
    src: zookeeper.stop.sh
    dest: /home/vishnunimmalapudi/confluent.temp/service/zookeeper/
    owner: root
    mode: 777
  become: yes
  notify:
    - restart zookeeper service



- name: enable zookeeper service on startup
  systemd: 
    name: zookeeper_ansible.service
    daemon_reload: yes
    enabled: yes
    masked: no
