---
- import_tasks: java.yml
  when: java_install

- import_tasks: register_vars.yml


- name: download-confluent-kafka
  shell: 'curl -O http://packages.confluent.io/archive/6.2/confluent-community-6.2.0.tar.gz'
  args:
    chdir: /home/vishnunimmalapudi/confluent.temp


- name: extract files from confluent.tar
  shell: 'tar xzf confluent-community-6.2.0.tar.gz'
  args:
    chdir: /home/vishnunimmalapudi/confluent.temp

- name: Configure server.properties
  template:
    src: server.properties.j2
    dest: /home/vishnunimmalapudi/confluent.temp/confluent-6.2.0/etc/kafka/server.properties

- name: Configure producer.properties
  template: 
    src: producer.properties.j2
    dest: /home/vishnunimmalapudi/confluent.temp/confluent-6.2.0/etc/kafka/producer.properties

- name: configure consumer.properties
  template:
    src: consumer.properties.j2
    dest: /home/vishnunimmalapudi/confluent.temp/confluent-6.2.0/etc/kafka/consumer.properties

- name: Configure schema-registry.properties
  template:
    src: schema-registry.properties.j2
    dest: /home/vishnunimmalapudi/confluent.temp/confluent-6.2.0/etc/schema-registry/schema-registry.properties

- name: Configure kafka-rest.properties
  template:
    src: kafka-rest.properties.j2
    dest: /home/vishnunimmalapudi/confluent.temp/confluent-6.2.0/etc/kafka-rest/kafka-rest.properties

- name: Configure zookeeper.properties
  template:
    src: zookeeper.properties.j2
    dest: /home/vishnunimmalapudi/confluent.temp/confluent-6.2.0/etc/kafka/zookeeper.properties

- name: Creates zookeeper cluster directories
  file: 
    path: /home/vishnunimmalapudi/confluent.temp/data/zoo-dataDir
    state: directory

- name: Configure zookeeper myid
  template:
    src: myid.j2
    dest: /home/vishnunimmalapudi/confluent.temp/data/zoo-dataDir/myid

- name: Install zookeeper as service
  copy: 
    src: zookeeper_ansible.service
    dest: /etc/systemd/system/
    owner: root 
    mode: 644
  notify:
    - restart zookeeper service

- name: Install kafka as service
  copy: 
    src: kafka_ansible.service
    dest: /etc/systemd/system/
    owner: root 
    mode: 644
  notify:
    - restart kafka service

- name: Install schema-registry as service
  copy: 
    src: schema-registry_ansible.service
    dest: /etc/systemd/system/
    owner: root 
    mode: 644
  notify:
    - restart schema-registry service

- name: Install kafka-rest as service
  copy: 
    src: kafka-rest_ansible.service
    dest: /etc/systemd/system/
    owner: root 
    mode: 644
  notify:
    - restart kafka-rest service

- name: enable zookeeper service on startup
  systemd: 
    name: zookeeper_ansible.service
    daemon_reload: yes
    enabled: yes
    masked: no

- name: enable kafka service on startup
  systemd: 
    name: kafka_ansible.service
    daemon_reload: yes
    enabled: yes
    masked: no

- name: enable schema-registry service on startup
  systemd: 
    name: schema-registry_ansible.service
    daemon_reload: yes
    enabled: yes
    masked: no

- name: enable kafka-rest service on startup
  systemd: 
    name: kafka-rest_ansible.service
    daemon_reload: yes
    enabled: yes
    masked: no


