---

- import_tasks: register_vars.yml

- name: create directory if they don't exist
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: 0775
  loop:
    - /home/vishnunimmalapudi/confluent.temp/confluent
    - /home/vishnunimmalapudi/confluent.temp/java
    - /home/vishnunimmalapudi/confluent.temp/service/zookeeper
    - /home/vishnunimmalapudi/confluent.temp/service/kafka
    - /home/vishnunimmalapudi/confluent.temp/confluent/data/zoo-dataDir
    - /home/vishnunimmalapudi/confluent.temp/tmp/kafka-10-logs


- name: download-confluent-kafka
  shell: 'sudo curl -O http://packages.confluent.io/archive/6.2/confluent-community-6.2.0.tar.gz'
  args:
    chdir: /home/vishnunimmalapudi/confluent.temp/confluent


- name: extract files from confluent.tar
  shell: 'sudo tar xzf confluent-community-6.2.0.tar.gz'
  args:
    chdir: /home/vishnunimmalapudi/confluent.temp/confluent

- name: download-java
  shell: 'sudo curl -O https://download.java.net/java/GA/jdk11/13/GPL/openjdk-11.0.1_linux-x64_bin.tar.gz'
  args:
    chdir: /home/vishnunimmalapudi/confluent.temp/java


- name: extract files from java.tar
  shell: 'sudo tar xzf openjdk-11.0.1_linux-x64_bin.tar.gz'
  args:
    chdir: /home/vishnunimmalapudi/confluent.temp/java

- name: copy paste zoo props
  shell: 'sudo cp /home/vishnunimmalapudi/confluent.temp/confluent/confluent-6.2.0/etc/kafka/zookeeper.properties /home/vishnunimmalapudi/confluent.temp/service/zookeeper/zookeeper.properties'




- name: Configure zookeeper.properties
  template:
    src: zookeeper.properties.j2
    dest: /home/vishnunimmalapudi/confluent.temp/service/zookeeper/zookeeper.properties


- name: copy paste server props into service folder
  shell: 'sudo cp /home/vishnunimmalapudi/confluent.temp/confluent/confluent-6.2.0/etc/kafka/server.properties /home/vishnunimmalapudi/confluent.temp/service/kafka/server-1.properties'

- name: Configure server.properties
  template:
    src: server.properties.j2
    dest: /home/vishnunimmalapudi/confluent.temp/service/kafka/server-1.properties



- name: Creates zookeeper cluster directories
  file: 
    path: /home/vishnunimmalapudi/confluent.temp/confluent/data/zoo-dataDir
    state: directory

- name: Configure zookeeper myid
  template:
    src: myid.j2
    dest: /home/vishnunimmalapudi/confluent.temp/confluent/data/zoo-dataDir/myid

- name: Install zookeeper as service
  copy: 
    src: zookeeper_ansible.service
    dest: /etc/systemd/system/
    owner: root 
    mode: 777
  become: yes
  notify:
    - restart zookeeper service


- name: Install zookeeper.run
  copy:
    src: zookeeper.run.sh
    dest: /home/vishnunimmalapudi/confluent.temp/service/zookeeper/
    owner: root
    mode: 777
  become: yes
  

- name: Install zookeeper.stop
  copy:
    src: zookeeper.stop.sh
    dest: /home/vishnunimmalapudi/confluent.temp/service/zookeeper/
    owner: root
    mode: 777
  become: yes

- name: Install kafka as service
  copy:
    src: kafka_ansible@.service
    dest: /etc/systemd/system/
    owner: root
    mode: 644
  notify:
    - restart kafka service

- name: Install kafka.run
  copy:
    src: kafka.run.sh
    dest: /home/vishnunimmalapudi/confluent.temp/service/kafka/
    owner: root
    mode: 777
 

- name: Install kafka.stop
  copy:
    src: kafka.stop.sh
    dest: /home/vishnunimmalapudi/confluent.temp/service/kafka/
    owner: root
    mode: 777
 
- name: enable zookeeper service on startup
  systemd: 
    name: zookeeper_ansible.service
    daemon_reload: yes
    enabled: yes
    masked: no


- name: enable kafka service on startup
  systemd:
    name: kafka_ansible@1.service
    daemon_reload: yes
    enabled: yes
    masked: no



